server:
  port: 8080

spring:
  application:
    name: core-ai
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
logging:
  level:
    org.hibernate.SQL: debug